dbks_name                   = "Test-DBKS" 
location                    = "West Europe"
dbks_managed_RG             = "_AM-Dbks-RG"
vnet_name                   = "Test-VNet"
dbks_public_subnet_name     = "Test-Vnet-Dbks-Public-Subnet"
dbks_private_subnet_name    = "Test-Vnet-Dbks-Private-Subnet"
core_network_rg_name        = "_Network-RG" 
resource_group_name         = "_AM-RG"